### ISSUE TITLE
"Lightroom needs to configure your system for the 500px plug-in"

### ISSUE THREAD

**Issue by mathieucarbou** [500px/500pxPublisher.lrplugin#23]
I always get this message when Lightroom CC starts since the latest CC update.
Here is a screenhot: 
![Lightroom needs to configure your system for the 500px plug-in](http://i.imgur.com/yE7tmsp.png)

**Comment by dan753722** [comment]
yeah me too. It's annoying. Please explain what's happening or fix it :)

**Comment by benjamin-chan** [comment]
This issue just started happening with me as well. Lightroom 6.7 for Windows. 500px plugin version 1.10.

**Comment by gavinsharp** [comment]
Unfortunately this appears to be an issue with Lightroom, not something we can fix. The thread mentioned by Benjamin (https://forums.adobe.com/thread/1825559) offers some potential solutions.
