### ISSUE TITLE
Lua programming

### ISSUE THREAD

**Issue by paulocapucci** [500px/500pxPublisher.lrplugin#33]
I started programming about Lua I downloaded 500pxPublisher... I compiled bat error.

/Users/epics-paulinho/Lua/lua-5.1.4/src/lua: .../Lua/500pxPublisher.lrplugin-master/src/500pxAPI.lua:6: attempt to call global 'import' (a nil value)

local LrDate = import "LrDate" <= Error

What I need? What i will do?

Thank you,

Paulo

**Comment by danosipov** [comment]
@paulocapucci The plugin only works in the context of Adobe Lightroom - you can't execute it by itself. LrDate is provided by Lightroom.

**Comment by paulocapucci** [comment]
How doi execute it in Lightroom in a test enviroment?

**Comment by danosipov** [comment]
Not sure what you mean by "test environment". You should be able to install it as a Lightroom plugin, and should work.

**Comment by paulocapucci** [comment]
Its not a 500px plugin,im doing one myself and i need to test if it works/bugs , how can i make it? running it inside lightroom as a plugin should do the job?

**Comment by danosipov** [comment]
Yup. Check Lightroom SDK documentation for instructions on getting started

**Comment by paulocapucci** [comment]
im trying to programm the plugin,and im getting the lrDate error,even when i got the example one from Lightroom SDK , and i need to know whats working on my code,how can i compile it on my developer app? do i need any program to run it to test? any files to make it work?

**Comment by paulocapucci** [comment]
@danosipov
